### ISSUE TITLE
[BE/Feat] 회원 정보 조회, 회원 정보 수정

### ISSUE THREAD

**Issue by Park0720** [six-star-104/pawly#15]
In GitLab by @ppmm98 on Oct 31, 2024, 13:40

## 📔 Description

회원 정보 조회, 회원 정보 수정 기능

## 🐈 Todo

-   [x] 마이페이지 정보 조회
-   [x] 친구 정보 조회
-   [x] 닉네임 중복 체크
-   [x] 닉네임 변경
