### ISSUE TITLE
[FE/Feat] 롤링페이퍼 UI 구성

### ISSUE THREAD

**Issue by Park0720** [six-star-104/pawly#20]
In GitLab by @chlguddn1212 on Nov 1, 2024, 10:35

## 📔 Description

롤링페이퍼 페이지 구성 및 구현
## 🐈 Todo

-   [x] 롤링페이퍼 페이지 구현
-   [x] 포스트잇 생성 구현
-   [x] 포스트잇 수정 구현
-   [x] 포스트잇 삭제 구현
