### ISSUE TITLE
[FE/Feat] 도전과제 UI 구성

### ISSUE THREAD

**Issue by Park0720** [six-star-104/pawly#28]
In GitLab by @skadmstlrek on Nov 4, 2024, 13:35

## 📔 Description

도전과제 페이지 UI 만들기

## 🐈 Todo

-   [x] 진행중 / 완료됨 나누기
-   [x] 버튼 각각 다르게 설정
-   [x] 달성과제/전체 퍼센트 구현
