### ISSUE TITLE
[BE/Feat] 롤링페이퍼 종료/상세조회 수정

### ISSUE THREAD

**Issue by Park0720** [six-star-104/pawly#35]
In GitLab by @whd4638 on Nov 6, 2024, 11:01

## 📔 Description

롤링페이퍼 종료/상세 조회 수정
## 🐈 Todo

-   [x] 롤링페이퍼 종료시 우체통 같이 종료
-   [x] 롤링페이퍼 상세 조회시 배경색, 글자색 등 추가
-   [x] 롤링페이서 상세 조회시 삭제된 포스트잇 제거
