### ISSUE TITLE
[FE/Feat] 친구 신청 / 유저 검색

### ISSUE THREAD

**Issue by Park0720** [six-star-104/pawly#36]
In GitLab by @skadmstlrek on Nov 6, 2024, 11:01

## 📔 Description

친구 신청이랑 검색 기능 구현하려구요

## 🐈 Todo

-   [x] 전체 유저 검색
-   [x] 친구 검색 
-   [x] 친구 신청 / 수락 
-   [x] 친구 목록 / 요청 목록 조회
