### ISSUE TITLE
[FE/Feat] AR 기능 구현

### ISSUE THREAD

**Issue by Park0720** [six-star-104/pawly#6]
In GitLab by @chlguddn1212 on Oct 29, 2024, 09:12

## 📔 Description

AR 기본 환경 셋팅 및 개발
## 🐈 Todo

-   [x] 기본 환경 셋팅
-   [x] 우체통 모델 구현
-   [x] 우체통별 이름 구현
-   [x] 클릭 이벤트 구현
-   [x] 우체통 생성 기능 구현
-   [ ] 우체통 관련 주변 지도 추가 및 연동
-   [x] 우체통 삭제 구현
