### ISSUE TITLE
[BE/Fix] 신고 수정

### ISSUE THREAD

**Issue by Park0720** [six-star-104/pawly#64]
In GitLab by @alddlv81 on Nov 12, 2024, 17:33

## 📔 Description

신고 예외 추가, 신고할 때 신고 대상자의 count 올라가도록 수정

## 🐈 Todo

-   [x] 롤링페이퍼 신고 예외 추가
- [x] 받은 편지 신고 예외 추가
- [x] 신고 처리할 때 신고 대상자 count 올라가도록 수정
